sudo: required 
language: java
jdk:
  - openjdk13

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

before_install:
  - docker build -t quay.io/pancancer/pcawg-bwa-mem-workflow:2.7.0 .

install: 
  - pip2.7 install --user -r requirements.txt

script: 
  - mvn -B clean install
  - cwltool --non-strict --print-pre Dockstore.cwl
# cannot run, proper run would take too long - cwltool --non-strict Dockstore.cwl Dockstore_cwl.json
